Add bosh-lite stemcell to blessed_versions.json
[#102436344]

Signed-off-by: Mikhail Vyshegorodtsev <mvyshegorodtse@vmware.com>

diff --git a/scripts/generate_blessed_versions b/scripts/generate_blessed_versions
--- a/scripts/generate_blessed_versions
+++ b/scripts/generate_blessed_versions
@@ -1,92 +1,115 @@
 #!/bin/bash
 
-set -e -x
+set -eux -o pipefail
 
-pushd $(dirname $0)
-  SCRIPT_DIR=$(pwd)
-popd
+mydir="$(cd "$(dirname "$0")" && pwd)"
+cf_deployment_dir="$(cd "${mydir}/.." && pwd)"
 
-CF_DEPLOYMENT_DIR=$(cd $SCRIPT_DIR/.. && pwd)
+release_dir="$(cd "${mydir}/../outputs/releases" && pwd)"
+rm -rf "${release_dir}"
+mkdir -p "${release_dir}"
 
-RELEASE_DIR=${SCRIPT_DIR}/../outputs/releases
-rm -rf ${RELEASE_DIR}
-mkdir -p ${RELEASE_DIR}
+output_dir="$( cd "${mydir}/../outputs/create_release" && pwd)"
+rm -rf "${output_dir}"
+mkdir -p "${output_dir}"
 
-OUTPUT_DIR=${SCRIPT_DIR}/../outputs/create_release
-rm -rf ${OUTPUT_DIR}
-mkdir -p ${OUTPUT_DIR}
-
-if [ $# -ne 3 ]; then
-  echo "Usage: create_releases PATH_TO_CF_RELEASE PATH_TO_ETCD_RELEASE PATH_TO_CONSUL_RELEASE"
+if [ $# -ne 4 ]; then
+  echo "Usage: ${0} aws_stemcell_path bosh_lite_stemcell_path cf_release_path etcd_release_path"
   exit 1
 fi
 
-STEMCELL_PATH=$1
-CF_RELEASE_PATH=$2
-ETCD_RELEASE_PATH=$3
+aws_stemcell_path="${1:?}"
+bosh_lite_stemcell_path="${2:?}"
+cf_release_path="${3:?}"
+etcd_release_path="${4:?}"
 
-if [ ! -e ${STEMCELL_PATH} ]; then
-  echo "PATH_TO_STEMCELL is invalid"
+if [ ! -e "${aws_stemcell_path}" ]; then
+  echo "aws_stemcell_path is invalid"
   exit 1
 fi
 
-if [ ! -d ${CF_RELEASE_PATH} ]; then
-  echo "PATH_TO_CF_RELEASE is invalid"
+if [ ! -e "${bosh_lite_stemcell_path}" ]; then
+  echo "bosh_lite_stemcell_path is invalid"
   exit 1
 fi
 
-if [ ! -e ${ETCD_RELEASE_PATH} ]; then
-  echo "PATH_TO_ETCD_RELEASE is invalid"
+if [ ! -d "${cf_release_path}" ]; then
+  echo "cf_release_path is invalid"
   exit 1
 fi
 
+if [ ! -e "${etcd_release_path}" ]; then
+  echo "etcd_release_path is invalid"
+  exit 1
+fi
 
 export BOSH_USE_BUNDLER=true
 
-date=$(date +%s)
-
-pushd ${CF_RELEASE_PATH}
-  CF_RELEASE_COMMIT=$(git rev-parse HEAD)
+pushd "${cf_release_path}"
+  cf_release_commit=$(git rev-parse HEAD)
 popd
 
-ETCD_VERSION=$(tar -x -O -f ${ETCD_RELEASE_PATH} ./release.MF | grep -E '^version:' | grep -o -E "[0-9.]*[0-9]")
-ETCD_SHA=$(sha1sum ${ETCD_RELEASE_PATH} | awk '{print $1;}')
-STEMCELL_VERSION=$(tar -xOf ${STEMCELL_PATH} stemcell.MF | grep version | head -1 | grep -o -E "[0-9.]*[0-9]")
-STEMCELL_NAME=$(tar -xOf ${STEMCELL_PATH} stemcell.MF | grep name | head -1 | awk '{print $2;}')
-STEMCELL_SHA1=$(sha1sum ${STEMCELL_PATH} | awk '{print $1;}')
+etcd_version="$(tar -xOf "${etcd_release_path}" ./release.MF | grep -E '^version:' | grep -o -E "[0-9.]*[0-9]")"
+etcd_sha="$(sha1sum "${etcd_release_path}" | awk '{print $1;}')"
+
+stemcell_version() {
+  tar -xOf "${1}" stemcell.MF | grep version | head -1 | grep -o -E "[0-9.]*[0-9]"
+}
+
+stemcell_name() {
+  tar -xOf "${1}" stemcell.MF | grep name | head -1 | awk '{print $2;}'
+}
+
+stemcell_sha1() {
+  sha1sum "${1}" | awk '{print $1;}'
+}
+
+aws_stemcell_version="$(stemcell_version "${aws_stemcell_path}")"
+aws_stemcell_name="$(stemcell_name "${aws_stemcell_path}")"
+aws_stemcell_sha1="$(stemcell_sha1 "${aws_stemcell_path}")"
+
+bosh_lite_stemcell_version="$(stemcell_version "${bosh_lite_stemcell_path}")"
+bosh_lite_stemcell_name="$(stemcell_name "${bosh_lite_stemcell_path}")"
+bosh_lite_stemcell_sha1="$(stemcell_sha1 "${bosh_lite_stemcell_path}")"
 
 #prepare-deployments script relies on the `commit` tag for cf.
 #Currently prepare deployment uses this information naively by
 #calling grep. If you wish to cange this file to have more commits
 #then prepare-deployment will need to be updated as well.
-cat > $CF_DEPLOYMENT_DIR/blessed_versions.json <<EOF
+cat > "${cf_deployment_dir}/blessed_versions.json" <<EOF
 {
   "releases": [
     {
       "name": "cf",
-      "commit": "${CF_RELEASE_COMMIT}"
+      "commit": "${cf_release_commit}"
     },
     {
       "name": "etcd",
-      "version": "${ETCD_VERSION}",
-      "sha1": "${ETCD_SHA}",
-      "url": "https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=${ETCD_VERSION}"
+      "version": "${etcd_version}",
+      "sha1": "${etcd_sha}",
+      "url": "https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=${etcd_version}"
     }
   ],
   "stemcells": {
     "aws": {
-      "type": "${STEMCELL_NAME}",
-      "version": "${STEMCELL_VERSION}",
-      "url": "https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=${STEMCELL_VERSION}",
-      "sha1": "${STEMCELL_SHA1}"
+      "type": "${aws_stemcell_name}",
+      "version": "${aws_stemcell_version}",
+      "url": "https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=${aws_stemcell_version}",
+      "sha1": "${aws_stemcell_sha1}"
+    },
+    "bosh-lite": {
+      "type": "${bosh_lite_stemcell_name}",
+      "version": "${bosh_lite_stemcell_version}",
+      "url": "https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent?v=${bosh_lite_stemcell_version}",
+      "sha1": "${bosh_lite_stemcell_sha1}"
     }
   }
 }
 EOF
 
-cat $CF_DEPLOYMENT_DIR/blessed_versions.json
+cat "${cf_deployment_dir}/blessed_versions.json"
 
-git add $CF_DEPLOYMENT_DIR/blessed_versions.json
+git add "${cf_deployment_dir}/blessed_versions.json"
 git config user.name "CF MEGA BOT"
 git config user.email "cf-mega@pivotal.io"
 git commit -m "Update blessing"
